# config.toml íŒŒì¼
[theme]
primaryColor="green" 			# theme
#secondaryBackgroundColor="red" 		# side bar


[[pages]]
path = "app.py"
name = "Comment"
icon = "ğŸ’›"

path = "pages/age_salary.py"
name = "ì—°ë ¹ë³„ ì„ê¸ˆ ë° ê·¼ë¡œì‹œê°„"
icon = "ğŸ¦¦"
