# pages.toml

[[pages]]
path = "/mount/src/streamlit_big_data/app.py"
name = "Comment"
icon = "ğŸ’›"

[[pages]]
path = "/mount/src/streamlit_big_data/pages/age_salary.py"
name = "ì—°ë ¹ë³„ ì„ê¸ˆ ë° ê·¼ë¡œì‹œê°„"
icon = "ğŸ¦¦"

